### ISSUE TITLE
un-break vanity paste handling

### ISSUE THREAD

**Issue by buhman** [ptpb/pb#120]
```pytb
Traceback (most recent call last):
  File "/root/pbenv/src/flask/flask/app.py", line 1969, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/pbenv/src/flask/flask/app.py", line 1953, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/root/pbenv/src/flask/flask/app.py", line 1530, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/pbenv/src/flask/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/pbenv/src/flask/flask/app.py", line 1950, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/pbenv/src/flask/flask/app.py", line 1604, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/pbenv/src/flask/flask/app.py", line 1507, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/pbenv/src/flask/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/pbenv/src/flask/flask/app.py", line 1602, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/pbenv/src/flask/flask/app.py", line 1588, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/pb/pb/paste/views.py", line 51, in post
    paste = model.insert(stream, label=label)
  File "/srv/pb/pb/paste/model.py", line 47, in insert
    get_db().pastes.insert(d)
  File "/root/pbenv/lib/python3.4/site-packages/pymongo/collection.py", line 1926, in insert
    check_keys, manipulate, write_concern)
  File "/root/pbenv/lib/python3.4/site-packages/pymongo/collection.py", line 436, in _insert
    self.codec_options, sock_info)
  File "/root/pbenv/lib/python3.4/site-packages/pymongo/pool.py", line 237, in legacy_write
    return helpers._check_gle_response(response)
  File "/root/pbenv/lib/python3.4/site-packages/pymongo/helpers.py", line 227, in _check_gle_response
    raise DuplicateKeyError(details["err"], code, result)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error index: pb.pastes.$label_1  dup key: { : "~polyzen" }
```

**Comment by buhman** [comment]
Fixed in 77907cb7e69b694372e1dad6b0443ac754781ed0
